name: Deploy GameBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Uncomment and configure services if needed
    # services:
    #   redis:
    #     image: redis
    #     ports:
    #       - 6379:6379
    #     options: >-
    #       --health-cmd "redis-cli ping"
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio httpx
    
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        VECTOR_STORE_ID: ${{ secrets.VECTOR_STORE_ID }}
        CI: 'true'  # This will make the test skip integration tests
      run: |
        python -m pip install pytest-asyncio
        python -m pytest -v tests/ -k "not integration"  # Skip integration tests in CI

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
        heroku --version
    
    - name: Login to Heroku
      run: |
        echo "Logging into Heroku..."
        heroku container:login
    
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        # Set environment variables on Heroku
        heroku config:set --app ${{ secrets.HEROKU_APP_NAME }} \
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          VECTOR_STORE_ID=${{ secrets.VECTOR_STORE_ID }} \
          HOST=0.0.0.0 \
          PORT=$PORT \
          ALLOWED_ORIGINS="*"
        
        # Add Heroku remote
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git || true
        
        # Deploy using Heroku buildpacks (simpler approach)
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main
        
        # Verify deployment
        heroku ps:scale web=1 --app ${{ secrets.HEROKU_APP_NAME }}
        heroku logs --app ${{ secrets.HEROKU_APP_NAME }} --tail
